/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'forest-accent': '#234A3A',
        'ink-black': '#1A1A1A',
        'ivory-base': '#FAFAF7',
        'primary': '#093325',
        'primary-container': '#234a3a',
        'on-primary': '#ffffff',
        'on-primary-container': '#8fb9a4',
        'primary-fixed': '#c1ecd6',
        'primary-fixed-dim': '#a6d0bb',
        'on-primary-fixed': '#002115',
        'on-primary-fixed-variant': '#274e3e',
        'inverse-primary': '#a6d0bb',
        'secondary': '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2dfde',
        'on-secondary-container': '#636262',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474746',
        'tertiary': '#482220',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#623735',
        'on-tertiary-container': '#dca19e',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#f5b7b4',
        'on-tertiary-fixed': '#331110',
        'on-tertiary-fixed-variant': '#663b39',
        'surface': '#f9f9f6',
        'surface-dim': '#dadad7',
        'surface-bright': '#f9f9f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f4f1',
        'surface-container': '#eeeeeb',
        'surface-container-high': '#e8e8e5',
        'surface-container-highest': '#e2e3e0',
        'on-surface': '#1a1c1b',
        'on-surface-variant': '#414844',
        'surface-tint': '#3f6655',
        'surface-variant': '#e2e3e0',
        'inverse-surface': '#2f312f',
        'inverse-on-surface': '#f1f1ee',
        'outline': '#717974',
        'outline-variant': '#c1c8c2',
        'background': '#f9f9f6',
        'on-background': '#1a1c1b',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'hairline-border': 'rgba(26, 26, 26, 0.1)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '80px',
        'margin-mobile': '24px',
        'container-max': '1320px',
        'unit': '4px',
        'gutter': '32px',
        'section-gap': '160px',
      },
      fontFamily: {
        'display-lg': ['Playfair Display', 'Georgia', 'serif'],
        'display-lg-mobile': ['Playfair Display', 'Georgia', 'serif'],
        'headline-md': ['Playfair Display', 'Georgia', 'serif'],
        'headline-sm': ['Playfair Display', 'Georgia', 'serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['48px', { lineHeight: '1.1', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['40px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-sm': ['28px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
